services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    volumes:
      - pgdata:/var/lib/postgresql
      - ./initdb.d:/docker-entrypoint-initdb.d

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=mypassword
      - ADMIN_USERS=postgres,admin
    ports:
      - "15432:5432"
    depends_on:
      - postgres

  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pgbouncer;Port=5432;Database=postgres;Username=user;Password=mypassword;Pooling=true;
    depends_on:
      - pgbouncer
    volumes:
      - ./WebApi/appsettings.Development.json:/app/appsettings.Development.json:ro
      - ./WebApi/appsettings.json:/app/appsettings.json:ro

volumes:
  pgdata:
