services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./initdb.d:/docker-entrypoint-initdb.d

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=mypassword
      - ADMIN_USERS=postgres,admin
    ports:
      - "15432:5432"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypassword
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  oms:
    build:
      context: .
      dockerfile: Oms/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - pgbouncer
      - rabbitmq
    volumes:
      - ./Oms/appsettings.Docker.json:/app/appsettings.Docker.json:ro
      - ./Oms/appsettings.json:/app/appsettings.json:ro

  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - pgbouncer
      - rabbitmq
    volumes:
      - ./Consumer/appsettings.Docker.json:/app/appsettings.Docker.json:ro
      - ./Consumer/appsettings.json:/app/appsettings.json:ro

volumes:
  pgdata:
  rabbitmqdata:
